# -*- mode: ruby -*-
# vi: set ft=ruby :


#  https://www.microcloudy.com/2018/12/24/droplet-run-centos-on-digitalocean-cloud-using-vagrant/
# https://github.com/devopsgroup-io/vagrant-digitalocean


Vagrant.configure("2") do |config|

	config.ssh.insert_key = false
	config.vm.box_check_update = false

	config.vm.define "quarkus_kafka_reactive" do |workspace_config|
    workspace_config.vm.box = "centos/7"
		workspace_config.vm.hostname = "quarkus-kafka-reactive"
		workspace_config.vm.network "private_network", ip: "192.168.11.12"
		workspace_config.vm.network "forwarded_port", guest: 8080, host: 8280
		workspace_config.vm.network "forwarded_port", guest: 8082, host: 8282
		workspace_config.vm.network "forwarded_port", guest: 8083, host: 8283
		workspace_config.vm.network "forwarded_port", guest: 8084, host: 8284
		workspace_config.vm.synced_folder "../src", "/home/vagrant/workspace", mount_options: ["dmode=775"]
		workspace_config.vm.provider "virtualbox" do |qkr_ws_config_local|
      	qkr_ws_config_local.name = "qkr_ws_config_local"
      	opts = ["modifyvm", :id, "--natdnshostresolver1", "on"]
      	qkr_ws_config_local.customize opts
#      	qkr_ws_config_local.memory = "2048"
      	qkr_ws_config_local.memory = "4096"
      	qkr_ws_config_local.cpus = "2"
      end
      workspace_config.vm.provision :shell, path: "bootstrap-vm.sh"
		end

end

