# -*- mode: ruby -*-
# vi: set ft=ruby :


#  https://www.microcloudy.com/2018/12/24/droplet-run-centos-on-digitalocean-cloud-using-vagrant/
# https://github.com/devopsgroup-io/vagrant-digitalocean


Vagrant.configure("2") do |config|

	config.ssh.insert_key = false
	config.vm.box_check_update = false

	config.vm.define "quarkus_samples" do |quarkus_samples_ws_config|
    quarkus_samples_ws_config.vm.box = "centos/7"
		quarkus_samples_ws_config.vm.hostname = "quarkus-samples"
		quarkus_samples_ws_config.vm.network "private_network", ip: "192.168.11.12"
		quarkus_samples_ws_config.vm.network "forwarded_port", guest: 8080, host: 8380
		quarkus_samples_ws_config.vm.network "forwarded_port", guest: 8082, host: 8382
		quarkus_samples_ws_config.vm.network "forwarded_port", guest: 8083, host: 8383
		quarkus_samples_ws_config.vm.network "forwarded_port", guest: 8084, host: 8384
		quarkus_samples_ws_config.vm.synced_folder "../src", "/home/vagrant/workspace", mount_options: ["dmode=775"]
		quarkus_samples_ws_config.vm.provider "virtualbox" do |qrks_smpls_ws_conf_local|
      	qrks_smpls_ws_conf_local.name = "qrks_smpls_ws_conf_local"
      	opts = ["modifyvm", :id, "--natdnshostresolver1", "on"]
      	qrks_smpls_ws_conf_local.customize opts
#      	qrks_smpls_ws_conf_local.memory = "2048"
      	qrks_smpls_ws_conf_local.memory = "4096"
      	qrks_smpls_ws_conf_local.cpus = "2"
      end
      quarkus_samples_ws_config.vm.provision :shell, path: "bootstrap-vm.sh"
		end

end

